# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aaed7425bfb77b6530a271d62dc7186d0b7c3182b1e6e5b1b809966339d00c814a4e2648881ffbd48683333022441e790226db9622d0236307064da1c4e8e13
  paypal_host: https://www.sandbox.paypal.com
  app_host_external: http://6cda898.ngrok.com
  app_host_internal: http://localhost:3000
  paypal_business_email: sprzedawca@flippery.org.pl

test:
  secret_key_base: e51ad4ce8ae2f64d1c096492a0a138d18aa175b5a154e2276a1dc3506ce479ffde91a906e27007298ed55a5e82a667831740c607830ab4916ec184d5456ec81d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host: https://www.paypal.com
  app_host_external: https://ppo.flippery.org.pl
  app_host_internal: https://ppo.flippery.org.pl
  paypal_business_email: paypal@flippery.org.pl
